module.exports = {
  ANALYZER: 'COZY_SCRIPTS_ANALYZER',
  BUILD_DIR: 'COZY_SCRIPTS_APP_BUILD_DIR',
  DEBUG: 'COZY_SCRIPTS_DEBUG',
  ESLINT_FIX: 'COZY_SCRIPTS_ESLINT_FIX',
  HOT: 'HOT_RELOAD',
  HOST: 'DEV_HOST',
  MANIFEST: 'COZY_SCRIPTS_APP_MANIFEST',
  PORT: 'DEV_PORT',
  SRC_DIR: 'COZY_SCRIPTS_APP_SRC_DIR',
  USE_PREACT: '__USE_PREACT__',
  USE_REACT: '__USE_REACT__',
  USE_VUE: '__USE_VUE__'
}
