module.exports = {
  ANALYZER: 'COZY_SCRIPTS_ANALYZER',
  BUILD_DIR: 'COZY_SCRIPTS_APP_BUILD_DIR',
  CONFIG: 'COZY_SCRIPTS_CONFIG',
  DEBUG: 'COZY_SCRIPTS_DEBUG',
  ENTRY_EXT: 'COZY_SCRIPTS_ENTRY_EXT',
  ESLINT_FIX: 'COZY_SCRIPTS_ESLINT_FIX',
  HOT: 'HOT_RELOAD',
  HOST: 'DEV_HOST',
  MANIFEST: 'COZY_SCRIPTS_APP_MANIFEST',
  PORT: 'DEV_PORT',
  SRC_DIR: 'COZY_SCRIPTS_APP_SRC_DIR',
  APP_PATH: 'COZY_SCRIPTS_APP_PATH',
  APP_NODE_MODULES: 'COZY_SCRIPTS_APP_NODE_MODULES',
  FORCE_PUBLIC: 'FORCE_PUBLIC',
  DEVTOOL: 'DEVTOOL'
}
